(cl:defpackage zkhy_stereo_d-srv
  (:use )
  (:export
   "CAMERAPARAMS"
   "<CAMERAPARAMS-REQUEST>"
   "CAMERAPARAMS-REQUEST"
   "<CAMERAPARAMS-RESPONSE>"
   "CAMERAPARAMS-RESPONSE"
   "ROTATIONMATRIX"
   "<ROTATIONMATRIX-REQUEST>"
   "ROTATIONMATRIX-REQUEST"
   "<ROTATIONMATRIX-RESPONSE>"
   "ROTATIONMATRIX-RESPONSE"
  ))

