// Generated by gencpp from file zkhy_stereo_d/CameraParams.msg
// DO NOT EDIT!


#ifndef ZKHY_STEREO_D_MESSAGE_CAMERAPARAMS_H
#define ZKHY_STEREO_D_MESSAGE_CAMERAPARAMS_H

#include <ros/service_traits.h>


#include <zkhy_stereo_d/CameraParamsRequest.h>
#include <zkhy_stereo_d/CameraParamsResponse.h>


namespace zkhy_stereo_d
{

struct CameraParams
{

typedef CameraParamsRequest Request;
typedef CameraParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraParams
} // namespace zkhy_stereo_d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::zkhy_stereo_d::CameraParams > {
  static const char* value()
  {
    return "b5a51179c7613aa6615125d7efe017e2";
  }

  static const char* value(const ::zkhy_stereo_d::CameraParams&) { return value(); }
};

template<>
struct DataType< ::zkhy_stereo_d::CameraParams > {
  static const char* value()
  {
    return "zkhy_stereo_d/CameraParams";
  }

  static const char* value(const ::zkhy_stereo_d::CameraParams&) { return value(); }
};


// service_traits::MD5Sum< ::zkhy_stereo_d::CameraParamsRequest> should match
// service_traits::MD5Sum< ::zkhy_stereo_d::CameraParams >
template<>
struct MD5Sum< ::zkhy_stereo_d::CameraParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::zkhy_stereo_d::CameraParams >::value();
  }
  static const char* value(const ::zkhy_stereo_d::CameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::zkhy_stereo_d::CameraParamsRequest> should match
// service_traits::DataType< ::zkhy_stereo_d::CameraParams >
template<>
struct DataType< ::zkhy_stereo_d::CameraParamsRequest>
{
  static const char* value()
  {
    return DataType< ::zkhy_stereo_d::CameraParams >::value();
  }
  static const char* value(const ::zkhy_stereo_d::CameraParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::zkhy_stereo_d::CameraParamsResponse> should match
// service_traits::MD5Sum< ::zkhy_stereo_d::CameraParams >
template<>
struct MD5Sum< ::zkhy_stereo_d::CameraParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::zkhy_stereo_d::CameraParams >::value();
  }
  static const char* value(const ::zkhy_stereo_d::CameraParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::zkhy_stereo_d::CameraParamsResponse> should match
// service_traits::DataType< ::zkhy_stereo_d::CameraParams >
template<>
struct DataType< ::zkhy_stereo_d::CameraParamsResponse>
{
  static const char* value()
  {
    return DataType< ::zkhy_stereo_d::CameraParams >::value();
  }
  static const char* value(const ::zkhy_stereo_d::CameraParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ZKHY_STEREO_D_MESSAGE_CAMERAPARAMS_H
