// Generated by gencpp from file zkhy_stereo_d/CameraParamsRequest.msg
// DO NOT EDIT!


#ifndef ZKHY_STEREO_D_MESSAGE_CAMERAPARAMSREQUEST_H
#define ZKHY_STEREO_D_MESSAGE_CAMERAPARAMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace zkhy_stereo_d
{
template <class ContainerAllocator>
struct CameraParamsRequest_
{
  typedef CameraParamsRequest_<ContainerAllocator> Type;

  CameraParamsRequest_()
    {
    }
  CameraParamsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraParamsRequest_

typedef ::zkhy_stereo_d::CameraParamsRequest_<std::allocator<void> > CameraParamsRequest;

typedef boost::shared_ptr< ::zkhy_stereo_d::CameraParamsRequest > CameraParamsRequestPtr;
typedef boost::shared_ptr< ::zkhy_stereo_d::CameraParamsRequest const> CameraParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace zkhy_stereo_d

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zkhy_stereo_d/CameraParamsRequest";
  }

  static const char* value(const ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::zkhy_stereo_d::CameraParamsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ZKHY_STEREO_D_MESSAGE_CAMERAPARAMSREQUEST_H
